module.exports = {
  products: [
    {
      _id: '1',
      name: 'Full Zip Running Shirts',
      category: 'Shoes',
      image: '/img/erik-mclean-ByjIzFupcHo-unsplash.jpg',
      price: 45.95,
      brand: 'Hiskywin',
      rating: 4,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Under Armour Women/s Charged Assert 10',
      category: 'Shoes',
      image: '/img/irene-kredenets-dwKiHoqqxk8-unsplash.jpg',
      price: 169.95,
      brand: 'Les Twins',
      rating: 6.0,
      numReviews: 30,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'Running Shirts',
      category: 'Shoes',
      image: '/img/irene-kredenets-KStSiM1UvPw-unsplash.jpg',
      price: 59.99,
      brand: 'ZARA',
      rating: 4.7,
      numReviews: 34,
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'New Balance Women/ Fresh Foam Roav V1 Sneaker',
      category: 'Shoes',
      image: '/img/malvestida-Rp-viEAP8Bo-unsplash.jpg',
      price: 159.95,
      brand: 'Nike Air',
      rating: 5.5,
      numReviews: 45,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Under Armour Unisex-Child Grade School Lockdown 6 Basketball Shoe',
      category: 'Shoes',
      image: '/img/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg',
      price: 119.95,
      brand: 'Nike',
      rating: 5.9,
      numReviews: 51,
      countInStock: 6,
    },
    {
      _id: '6',
      name: ' Travel Laptop Backpack, Business Anti Theft Slim',
      category: 'Shoes',
      image: '/img/sun-lingyan-_H0fjILH5Vw-unsplash.jpg',
      price: 49.95,
      brand: 'Hiskywin',
      rating: 4.9,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};